=== antoinecourtin/EbD_2018/cours_InitiationXML/XML/doc1.dtd
<!ELEMENT boutique (telephone*)>
<!ELEMENT telephone (marque, modele, dispo)>
<!ELEMENT marque (#PCDATA)>
<!ELEMENT modele (#PCDATA)>
<!ELEMENT dispo (#PCDATA)>

=== antoinecourtin/EbD_2018/XML/boutique_v1.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet href="xslforboutique_v1.xsl" type="text/xsl"?>

<!DOCTYPE boutique SYSTEM "doc1.dtd">

<boutique>
  <telephone id="1">
    <marque>Samsung</marque>
    <modele>Galaxy S3</modele>
    <dispo>Oui</dispo>
  </telephone>

  <telephone id="2">
    <marque>Apple</marque>
    <modele>iPhone 4</modele>
    <dispo>Oui</dispo>
  </telephone>
  <telephone id="3">
    <marque>Nokia</marque>
    <modele>Lumia 800</modele>
    <dispo>Non</dispo>
  </telephone>
  <telephone id="4">
    <marque>Nokia</marque>
    <modele>Lumia 1900</modele>
    <dispo>Oui</dispo>
  </telephone>
</boutique>

=== antoinecourtin/EbD_2018/cours_InitiationXML/XML/boutique_v4.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet href="xslforboutique_v4.xsl" type="text/xsl"?>

<!DOCTYPE boutique SYSTEM "doc1.dtd">

<boutique>
  <telephone id="1">
    <marque>Samsung</marque>
    <modele nouveaute="non">Galaxy S3</modele>
    <dispo>Oui</dispo>
    <couleur>Bleu</couleur>
  </telephone>

  <telephone id="2">
    <marque>Apple</marque>
    <modele nouveaute="non">iPhone 4</modele>
    <dispo>Oui</dispo>
    <couleur>Noir</couleur>

  </telephone>
  <telephone id="3">
    <marque>Nokia</marque>
    <modele nouveaute="non">Lumia 800</modele>
    <dispo>Non</dispo>
    <couleur>Rose</couleur>

  </telephone>
  <telephone id="4">
    <marque>Nokia</marque>
    <modele nouveaute="oui">Lumia 1900</modele>
    <dispo>Oui</dispo>
    <couleur>Vert</couleur>
  </telephone>
</boutique>

=== antoinecourtin/EbD_2018/XML/testboutique.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet href="xslforboutique.xsl" type="text/xsl"?>

<!DOCTYPE boutique SYSTEM "doc1.dtd">

<boutique>
  <telephone>
    <marque>Samsung</marque>
    <modele>Galaxy S3</modele>
    <dispo>Oui</dispo>
  </telephone>

  <telephone>
    <marque>Apple</marque>
    <modele>iPhone 4</modele>
    <dispo>Oui</dispo>

  </telephone>

  <telephone>
    <marque>Nokia</marque>
    <modele>Lumia 800</modele>
    <dispo>Non</dispo>
  </telephone>
</boutique>
